services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoem-server
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:rw,cached
    environment:
      - DATABASE_URL=postgres://alqasim:alzakwani@db:5432/todoem?sslmode=disable
      - SECRET_KEY=xqcknM1ICw65eHLPB7+0UPgT2sdayTvIm0bRKhA+Oug=
    command: cargo watch -q -c -w src/ -x run
    networks:
      - todoem

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: todoem-db
    user: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=alqasim
      - POSTGRES_PASSWORD=alzakwani
      - POSTGRES_DB=todoem
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alqasim -d todoem"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todoem

volumes:
  db-data:

networks:
  todoem:
